#!/bin/bash
# Copyright 2021 Sony Semiconductors Israel, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================


echo "Publish Release"
version=$1 # first argument is the current release
echo "Releasing version:$1"
#########################################
# Making a tag
#########################################
git tag $version
git push origin $version
#########################################
# Build python package
#########################################
python setup.py sdist bdist_wheel --new_version $1 --repository=http://piprep-ub18:8080/
#########################################
# Upload to pypi server
#########################################
# twine upload dist/*

