#!/bin/bash
# Copyright 2021 Sony Semiconductors Israel, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================


echo "Testing Publish Release"
version=$(python -c 'import model_compression_toolkit; print(model_compression_toolkit.__version__)')
echo "Releasing version:$version"
#########################################
# Making a tag
#########################################
git tag -a $version -m "Release $version"
git push origin $version
#########################################
# Build python package
#########################################
python setup.py sdist bdist_wheel
#########################################
# Upload to pypi server
#########################################
twine upload --repository testpypi dist/* --verbose
#########################################
# Remove tag from local and origin
#########################################
git tag -d $version
git push --delete origin $version

