name: Run Keras Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      tf-version:
        required: true
        type: string

jobs:
  run-tensorflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow==${{ inputs.tf-version }} sony-custom-layers
      - name: Run unittests
        # Some tests are sensitive to memory because we use tf gradients on a multi-thread/process
        # CPU environment (https://github.com/tensorflow/tensorflow/issues/41718).
        # For this reason, if we run them in such an environment, we need to run them first non-parallel separately.
        run: |
          python -m unittest discover tests/keras_tests -v
          

